# Retrieval Evaluation Notebook (PFE)

Notebook d'audit et de test de la phase retrieval (keyword / vector / hybrid) sur les index locaux.

Objectif:
- verifier que la retrieval fonctionne reellement,
- comparer les modes,
- tester les filtres metadata supportes,
- controler l'absence de fuite PII evidente,
- produire un verdict demo/experimental.

## 1) Prerequisites

Ce notebook suppose que les etapes precedentes sont deja executees:

1. extraction
2. chunking
3. anonymization
4. indexing

Artefacts attendus:
- `data/indexes/medical_rag.sqlite`
- `data/indexes/qdrant/`

Si Qdrant local est locke par un autre process, les tests vector/hybrid peuvent echouer.

In [1]:
from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

import pandas as pd
from IPython.display import Markdown, display


def find_repo_root(start: Path) -> Path:
    current = start.resolve()
    for c in [current] + list(current.parents):
        if (c / 'scripts' / 'retrieval').exists() and (c / 'data').exists():
            return c
    raise RuntimeError('Impossible de localiser la racine du repo.')


repo_root = find_repo_root(Path.cwd())
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

INDEX_DIR = repo_root / 'data' / 'indexes'
SQLITE_PATH = INDEX_DIR / 'medical_rag.sqlite'
QDRANT_DIR = INDEX_DIR / 'qdrant'
COLLECTION = 'medical_chunks'

print('Repo root:', repo_root)
print('Index dir :', INDEX_DIR)
print('SQLite    :', SQLITE_PATH)
print('Qdrant dir:', QDRANT_DIR)

Repo root: /home/onizuka/Bureau/PFE/medical-rag-platform
Index dir : /home/onizuka/Bureau/PFE/medical-rag-platform/data/indexes
SQLite    : /home/onizuka/Bureau/PFE/medical-rag-platform/data/indexes/medical_rag.sqlite
Qdrant dir: /home/onizuka/Bureau/PFE/medical-rag-platform/data/indexes/qdrant

In [3]:
from scripts.retrieval.search import SearchEngine
from scripts.retrieval.models import RetrievalFilters

# Verification de presence des artefacts
checks = {
    'sqlite_exists': SQLITE_PATH.exists(),
    'qdrant_dir_exists': QDRANT_DIR.exists(),
    'indexing_report_exists': (INDEX_DIR / 'indexing_report.json').exists(),
    'index_manifest_exists': (INDEX_DIR / 'index_manifest.json').exists(),
}
print(json.dumps(checks, indent=2, ensure_ascii=False))

if not checks['sqlite_exists']:
    raise FileNotFoundError(f'SQLite manquant: {SQLITE_PATH}')
if not checks['qdrant_dir_exists']:
    raise FileNotFoundError(f'Qdrant dir manquant: {QDRANT_DIR}')

{
  "sqlite_exists": true,
  "qdrant_dir_exists": true,
  "indexing_report_exists": true,
  "index_manifest_exists": true
}

In [4]:
# Initialisation du moteur retrieval
engine = SearchEngine(
    sqlite_path=SQLITE_PATH,
    qdrant_dir=QDRANT_DIR,
    collection=COLLECTION,
)
print('SearchEngine initialisé.')

SearchEngine initialisé.

In [5]:
def truncate(text: str | None, n: int = 220) -> str:
    t = (text or '').strip()
    return t if len(t) <= n else t[: n - 3] + '...'


def run_query(query: str, mode: str = 'hybrid', top_k: int = 5, filters: RetrievalFilters | None = None, expand_context: bool = False):
    filters = filters or RetrievalFilters()
    resp = engine.search(
        query=query,
        mode=mode,
        top_k=top_k,
        filters=filters,
        expand_context=expand_context,
    )
    return resp


def response_to_table(resp, *, query: str, mode: str, top_k: int):
    rows = []
    for i, r in enumerate(resp.top_results[:top_k], start=1):
        m = r.metadata or {}
        rows.append({
            'query': query,
            'mode': mode,
            'top_k': top_k,
            'rank': i,
            'chunk_id': r.chunk_id,
            'doc_id': r.doc_id,
            'chunk_type': r.chunk_type,
            'score_vector': r.score_vector,
            'score_keyword': r.score_keyword,
            'score_hybrid': r.score_hybrid,
            'analyte': m.get('analyte'),
            'value_raw': m.get('value_raw'),
            'unit': m.get('unit'),
            'reference_range': m.get('reference_range'),
            'previous_result': m.get('previous_result'),
            'page_number': r.page_number,
            'row_index': m.get('row_index'),
            'source_kind': m.get('source_kind'),
            'source_pdf': r.source_pdf,
            'excerpt': truncate(r.text_preview, 220),
        })
    return pd.DataFrame(rows)


def first_hit_rank(df: pd.DataFrame, keywords: list[str]) -> int | None:
    if df.empty:
        return None
    kws = [k.lower() for k in keywords]
    for _, row in df.iterrows():
        blob = ' '.join([
            str(row.get('analyte') or ''),
            str(row.get('excerpt') or ''),
            str(row.get('chunk_type') or ''),
        ]).lower()
        if any(k in blob for k in kws):
            return int(row['rank'])
    return None

## 2) Smoke tests (manual)

Ces tests verifient rapidement que la retrieval retourne des chunks lisibles.

In [6]:
smoke_queries = [
    'trichuris trichiura',
    'albumine 5 g/l',
]

smoke_tables = []
for q in smoke_queries:
    resp = run_query(q, mode='hybrid', top_k=5, filters=RetrievalFilters(), expand_context=True)
    df = response_to_table(resp, query=q, mode='hybrid', top_k=5)
    smoke_tables.append(df)
    display(Markdown(f"### Query: `{q}`"))
    display(df)
    display(Markdown(f"Context chunks: `{len(resp.context_chunks)}`"))

/home/onizuka/Bureau/PFE/medical-rag-platform/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Fetching 30 files: 100%|██████████| 30/30 [00:00<00:00, 88862.37it/s]
Loading weights: 100%|██████████| 391/391 [00:00<00:00, 26553.53it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1128.71it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00,  7.98it/s]

### Query: `trichuris trichiura`

,query,mode,top_k,rank,chunk_id,doc_id,chunk_type,score_vector,score_keyword,score_hybrid,analyte,value_raw,unit,reference_range,previous_result,page_number,row_index,source_kind,source_pdf,excerpt
0,trichuris trichiura,hybrid,5,1,chk_report_exam_section_resultat_final_part_01,report,exam_section,0.492319,19.647114,0.032522,NaN,NaN,NaN,None,None,1,None,None,docs/report.pdf,RÉSULTAT FINAL: TRICHURIS TRICHIURA RÉSULTAT F...
1,trichuris trichiura,hybrid,5,2,chk_report_clinical_result_result_resultat_fin...,report,clinical_result,0.550785,19.066094,0.032522,,TRICHURIS TRICHIURA,,None,None,1,None,None,docs/report.pdf,RÉSULTAT FINAL: RÉSULTAT FINAL = TRICHURIS TRI...
2,trichuris trichiura,hybrid,5,3,chk_report_12_lab_result_result_resultats_biol...,report_12,lab_result,0.386512,NaN,0.015873,Triglycérides,4.3,g/l,None,None,2,None,None,docs/report (12).pdf,Résultat de laboratoire: Triglycérides = 4.3 g...
3,trichuris trichiura,hybrid,5,4,chk_report_16_lab_result_result_resultats_biol...,report_16,lab_result,0.384560,NaN,0.015625,TSHus,"55,00",mUI/L,None,None,1,None,None,docs/report (16).pdf,"Résultat de laboratoire: TSHus = 55,00 mUI/L. ..."
4,trichuris trichiura,hybrid,5,5,chk_report_11_lab_result_result_resultats_biol...,report_11,lab_result,0.383303,NaN,0.015385,TSHus,"2,00",mUI/L,None,None,1,None,None,docs/report (11).pdf,"Résultat de laboratoire: TSHus = 2,00 mUI/L. V..."

Context chunks: `8`

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1921.35it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00,  7.45it/s]

### Query: `albumine 5 g/l`

,query,mode,top_k,rank,chunk_id,doc_id,chunk_type,score_vector,score_keyword,score_hybrid,analyte,value_raw,unit,reference_range,previous_result,page_number,row_index,source_kind,source_pdf,excerpt
0,albumine 5 g/l,hybrid,5,1,chk_report_8_lab_result_result_resultats_biolo...,report_8,lab_result,0.677811,9.291907,0.032522,Albumine,5,g/l,None,None,1.0,None,None,docs/report (8).pdf,Résultat de laboratoire: Albumine = 5 g/l. Val...
1,albumine 5 g/l,hybrid,5,2,chk_report_8_exam_section_resultats_biologique...,report_8,exam_section,0.679856,9.139223,0.032522,NaN,NaN,NaN,None,None,NaN,None,None,docs/report (8).pdf,Section médicale: Résultats biologiques. Nombr...
2,albumine 5 g/l,hybrid,5,3,chk_report_29_lab_result_result_resultats_biol...,report_29,lab_result,0.664399,NaN,0.015873,Albumine,38.11,g/l,None,None,1.0,None,None,docs/report (29).pdf,Résultat de laboratoire: Albumine = 38.11 g/l....
3,albumine 5 g/l,hybrid,5,4,chk_report_10_lab_result_result_resultats_biol...,report_10,lab_result,0.659281,NaN,0.015625,Albumine,8,g/l,None,None,1.0,None,None,docs/report (10).pdf,Résultat de laboratoire: Albumine = 8 g/l. Val...
4,albumine 5 g/l,hybrid,5,5,chk_report_12_lab_result_result_resultats_biol...,report_12,lab_result,0.656274,NaN,0.015385,Albumine,40,g/l,None,None,1.0,None,None,docs/report (12).pdf,Résultat de laboratoire: Albumine = 40 g/l. Va...

Context chunks: `4`

## 3) Exact analyte queries (keyword vs vector vs hybrid)

In [7]:
exact_queries = {
    'calcitonine': ['calcitonine'],
    'peptide c': ['peptide c'],
    'insuline': ['insuline'],
    'pro bnp': ['pro bnp', 'nt-probnp', 'nt probnp'],
    'tshus': ['tshus', 'tsh'],
    'ferritine': ['ferritine'],
    'vitamine d': ['vitamine d'],
    'trichuris': ['trichuris'],
    'lithium': ['lithium'],
    'crp': ['crp', 'proteine c reactive'],
}

modes = ['keyword', 'vector', 'hybrid']
exact_rows = []
exact_detail = []

for q, clues in exact_queries.items():
    for mode in modes:
        try:
            resp = run_query(q, mode=mode, top_k=5, filters=RetrievalFilters(), expand_context=False)
            df = response_to_table(resp, query=q, mode=mode, top_k=5)
            exact_detail.append(df)
            rank = first_hit_rank(df, clues)
            exact_rows.append({
                'query': q,
                'mode': mode,
                'hit@1': rank == 1,
                'hit@3': (rank is not None and rank <= 3),
                'hit@5': (rank is not None and rank <= 5),
                'first_hit_rank': rank,
                'top1_chunk_id': None if df.empty else df.iloc[0]['chunk_id'],
                'top1_doc_id': None if df.empty else df.iloc[0]['doc_id'],
                'top1_chunk_type': None if df.empty else df.iloc[0]['chunk_type'],
            })
        except Exception as exc:
            exact_rows.append({
                'query': q,
                'mode': mode,
                'error': repr(exc),
                'hit@1': False,
                'hit@3': False,
                'hit@5': False,
                'first_hit_rank': None,
            })

exact_df = pd.DataFrame(exact_rows)
display(exact_df)

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 1970.08it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00,  8.78it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 3477.86it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2263.52it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00,  8.70it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 3034.95it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 10.16it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 3916.25it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00,  8.87it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2878.73it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00,  8.93it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2959.99it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00,  8.43it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2843.60it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00,  8.64it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2598.70it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00,  8.21it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 3398.95it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00,  8.07it/s]

,query,mode,hit@1,hit@3,hit@5,first_hit_rank,top1_chunk_id,top1_doc_id,top1_chunk_type
0,calcitonine,keyword,True,True,True,1,chk_report_1_lab_result_result_resultats_biolo...,report_1,lab_result
1,calcitonine,vector,True,True,True,1,chk_report_11_lab_result_result_resultats_biol...,report_11,lab_result
2,calcitonine,hybrid,True,True,True,1,chk_report_11_lab_result_result_resultats_biol...,report_11,lab_result
3,peptide c,keyword,True,True,True,1,chk_report_1_lab_result_result_resultats_biolo...,report_1,lab_result
4,peptide c,vector,True,True,True,1,chk_report_11_lab_result_result_resultats_biol...,report_11,lab_result
5,peptide c,hybrid,True,True,True,1,chk_report_1_lab_result_result_resultats_biolo...,report_1,lab_result
6,insuline,keyword,True,True,True,1,chk_report_28_exam_section_resultats_biologiqu...,report_28,exam_section
7,insuline,vector,True,True,True,1,chk_report_28_exam_section_resultats_biologiqu...,report_28,exam_section
8,insuline,hybrid,True,True,True,1,chk_report_28_exam_section_resultats_biologiqu...,report_28,exam_section
9,pro bnp,keyword,True,True,True,1,chk_report_17_lab_result_result_resultats_biol...,report_17,lab_result
10,pro bnp,vector,True,True,True,1,chk_report_17_lab_result_result_resultats_biol...,report_17,lab_result
11,pro bnp,hybrid,True,True,True,1,chk_report_17_lab_result_result_resultats_biol...,report_17,lab_result
12,tshus,keyword,True,True,True,1,chk_report_1_lab_result_result_resultats_biolo...,report_1,lab_result
13,tshus,vector,True,True,True,1,chk_report_16_lab_result_result_resultats_biol...,report_16,lab_result
14,tshus,hybrid,True,True,True,1,chk_report_1_lab_result_result_resultats_biolo...,report_1,lab_result
15,ferritine,keyword,True,True,True,1,chk_report_30_exam_section_resultats_biologiqu...,report_30,exam_section
16,ferritine,vector,True,True,True,1,chk_report_30_exam_section_resultats_biologiqu...,report_30,exam_section
17,ferritine,hybrid,True,True,True,1,chk_report_30_exam_section_resultats_biologiqu...,report_30,exam_section
18,vitamine d,keyword,True,True,True,1,chk_report_9_exam_section_resultats_biologique...,report_9,exam_section
19,vitamine d,vector,True,True,True,1,chk_report_31_lab_result_result_resultats_biol...,report_31,lab_result
20,vitamine d,hybrid,True,True,True,1,chk_report_9_exam_section_resultats_biologique...,report_9,exam_section
21,trichuris,keyword,True,True,True,1,chk_report_exam_section_resultat_final_part_01,report,exam_section
22,trichuris,vector,True,True,True,1,chk_report_clinical_result_result_resultat_fin...,report,clinical_result
23,trichuris,hybrid,True,True,True,1,chk_report_exam_section_resultat_final_part_01,report,exam_section
24,lithium,keyword,True,True,True,1,chk_report_15_lab_result_result_resultats_biol...,report_15,lab_result
25,lithium,vector,True,True,True,1,chk_report_15_lab_result_result_resultats_biol...,report_15,lab_result
26,lithium,hybrid,True,True,True,1,chk_report_15_lab_result_result_resultats_biol...,report_15,lab_result
27,crp,keyword,True,True,True,1,chk_report_10_lab_result_result_resultats_biol...,report_10,lab_result
28,crp,vector,True,True,True,1,chk_report_10_lab_result_result_resultats_biol...,report_10,lab_result
29,crp,hybrid,True,True,True,1,chk_report_10_lab_result_result_resultats_biol...,report_10,lab_result

## 4) Semantic queries (keyword vs vector vs hybrid)

Ces requetes servent a voir si vector/hybrid apportent un gain sur des formulations plus libres.

In [8]:
semantic_queries = {
    'resultat hormonal avec valeur de reference': ['tsh', 't4 libre', 'calcitonine', 'insuline', 'peptide c'],
    'resultat parasitologie positif': ['trichuris', 'ankylostoma', 'oeufs'],
    'resultat avec valeur superieure a la reference': ['>', 'eleve', 'high', 'above'],
    'resultat avec ancienne valeur': ['resultat anterieur', 'ancienne valeur', 'anterieur'],
    'analyse thyroidienne': ['tsh', 't4 libre', 't3 libre', 'anti-tpo', 'anti-tg'],
    'resultat biologique sans unite': ['non specifiee', 'unit_missing', 'sans unite'],
}

semantic_rows = []
for q, clues in semantic_queries.items():
    for mode in modes:
        try:
            resp = run_query(q, mode=mode, top_k=5, filters=RetrievalFilters(), expand_context=False)
            df = response_to_table(resp, query=q, mode=mode, top_k=5)
            rank = first_hit_rank(df, clues)
            semantic_rows.append({
                'query': q,
                'mode': mode,
                'hit@1': rank == 1,
                'hit@3': (rank is not None and rank <= 3),
                'hit@5': (rank is not None and rank <= 5),
                'first_hit_rank': rank,
                'top1_chunk_type': None if df.empty else df.iloc[0]['chunk_type'],
                'top1_doc_id': None if df.empty else df.iloc[0]['doc_id'],
            })
        except Exception as exc:
            semantic_rows.append({
                'query': q,
                'mode': mode,
                'error': repr(exc),
                'hit@1': False,
                'hit@3': False,
                'hit@5': False,
                'first_hit_rank': None,
            })

semantic_df = pd.DataFrame(semantic_rows)
display(semantic_df)

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2159.79it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00,  7.77it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2592.28it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00,  8.89it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2786.91it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00,  9.13it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2514.57it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00,  8.60it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2299.51it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 10.02it/s]
pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 2598.70it/s]
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00,  7.84it/s]

,query,mode,hit@1,hit@3,hit@5,first_hit_rank,top1_chunk_type,top1_doc_id
0,resultat hormonal avec valeur de reference,keyword,False,False,False,None,NaN,NaN
1,resultat hormonal avec valeur de reference,vector,False,False,False,None,lab_result,report_10
2,resultat hormonal avec valeur de reference,hybrid,False,False,False,None,lab_result,report_10
3,resultat parasitologie positif,keyword,False,False,False,None,NaN,NaN
4,resultat parasitologie positif,vector,False,False,False,None,exam_section,report
5,resultat parasitologie positif,hybrid,False,False,False,None,exam_section,report
6,resultat avec valeur superieure a la reference,keyword,False,False,False,None,NaN,NaN
7,resultat avec valeur superieure a la reference,vector,False,False,False,None,lab_result,report_29
8,resultat avec valeur superieure a la reference,hybrid,False,False,False,None,lab_result,report_29
9,resultat avec ancienne valeur,keyword,False,False,False,None,NaN,NaN
10,resultat avec ancienne valeur,vector,False,False,False,None,lab_result,report_1
11,resultat avec ancienne valeur,hybrid,False,False,False,None,lab_result,report_1
12,analyse thyroidienne,keyword,False,False,False,None,NaN,NaN
13,analyse thyroidienne,vector,False,False,False,None,exam_section,report_1
14,analyse thyroidienne,hybrid,False,False,False,None,exam_section,report_1
15,resultat biologique sans unite,keyword,False,False,False,None,NaN,NaN
16,resultat biologique sans unite,vector,False,False,False,None,exam_section,report_5
17,resultat biologique sans unite,hybrid,False,False,False,None,exam_section,report_5

## 5) Metadata filters

Filtres supportes par `RetrievalFilters`:
- `document_type`, `doc_id`, `patient_id`, `sample_id`, `request_date`, `sample_type`, `chunk_type`, `source_pdf`

Non supportes directement dans le filtre actuel:
- `analyte_norm`
- `section`
- `source_kind`

Ces derniers peuvent etre verifies a posteriori dans les metadata retournees.

In [9]:
filter_cases = [
    ('doc_id=report_1', RetrievalFilters(doc_id='report_1')),
    ('chunk_type=lab_result', RetrievalFilters(chunk_type='lab_result')),
    ('document_type=biology_report', RetrievalFilters(document_type='biology_report')),
    ('sample_type=SANG', RetrievalFilters(sample_type='SANG')),
    ('source_pdf=docs/report (1).pdf', RetrievalFilters(source_pdf='docs/report (1).pdf')),
]

filter_rows = []
for label, f in filter_cases:
    for mode in modes:
        try:
            resp = run_query('calcitonine', mode=mode, top_k=5, filters=f, expand_context=False)
            df = response_to_table(resp, query='calcitonine', mode=mode, top_k=5)
            all_match = True
            if not df.empty:
                if label == 'doc_id=report_1':
                    all_match = bool((df['doc_id'] == 'report_1').all())
                elif label == 'chunk_type=lab_result':
                    all_match = bool((df['chunk_type'] == 'lab_result').all())
                elif label == 'document_type=biology_report':
                    # available in metadata only, use response object
                    all_match = all((r.document_type == 'biology_report') for r in resp.top_results)
                elif label == 'source_pdf=docs/report (1).pdf':
                    all_match = bool((df['source_pdf'] == 'docs/report (1).pdf').all())
            filter_rows.append({
                'filter': label,
                'mode': mode,
                'top_count': len(resp.top_results),
                'all_match_filter': all_match,
                'top1_doc_id': None if df.empty else df.iloc[0]['doc_id'],
                'top1_chunk_type': None if df.empty else df.iloc[0]['chunk_type'],
            })
        except Exception as exc:
            filter_rows.append({'filter': label, 'mode': mode, 'error': repr(exc)})

filter_df = pd.DataFrame(filter_rows)
display(filter_df)

,filter,mode,top_count,all_match_filter,top1_doc_id,top1_chunk_type
0,doc_id=report_1,keyword,4,True,report_1,lab_result
1,doc_id=report_1,vector,5,True,report_1,lab_result
2,doc_id=report_1,hybrid,5,True,report_1,lab_result
3,chunk_type=lab_result,keyword,3,True,report_1,lab_result
4,chunk_type=lab_result,vector,5,True,report_11,lab_result
5,chunk_type=lab_result,hybrid,5,True,report_11,lab_result
6,document_type=biology_report,keyword,5,True,report_1,lab_result
7,document_type=biology_report,vector,5,True,report_11,lab_result
8,document_type=biology_report,hybrid,5,True,report_11,lab_result
9,sample_type=SANG,keyword,5,True,report_1,lab_result
10,sample_type=SANG,vector,5,True,report_11,lab_result
11,sample_type=SANG,hybrid,5,True,report_11,lab_result
12,source_pdf=docs/report (1).pdf,keyword,4,True,report_1,lab_result
13,source_pdf=docs/report (1).pdf,vector,5,True,report_1,lab_result
14,source_pdf=docs/report (1).pdf,hybrid,5,True,report_1,lab_result

## 6) Aggregate metrics (simple)

Métriques calculées:
- Hit@1
- Hit@3
- Hit@5

Sur deux lots:
- exact queries
- semantic queries

In [10]:
def summarize_hits(df: pd.DataFrame, label: str) -> pd.DataFrame:
    out = []
    for mode, g in df.groupby('mode'):
        ok = g[~g.get('error', pd.Series([None]*len(g))).notna()] if 'error' in g.columns else g
        n = len(ok)
        out.append({
            'suite': label,
            'mode': mode,
            'queries': n,
            'hit@1': float(ok['hit@1'].mean()) if n else 0.0,
            'hit@3': float(ok['hit@3'].mean()) if n else 0.0,
            'hit@5': float(ok['hit@5'].mean()) if n else 0.0,
        })
    return pd.DataFrame(out)

summary_df = pd.concat([
    summarize_hits(exact_df, 'exact'),
    summarize_hits(semantic_df, 'semantic'),
], ignore_index=True)

display(summary_df)

      suite     mode  queries  hit@1  hit@3  hit@5
0     exact   hybrid       10    1.0    1.0    1.0
1     exact  keyword       10    1.0    1.0    1.0
2     exact   vector       10    1.0    1.0    1.0
3  semantic   hybrid        6    0.0    0.0    0.0
4  semantic  keyword        6    0.0    0.0    0.0
5  semantic   vector        6    0.0    0.0    0.0

## 7) Anti-PII sanity check on retrieval outputs

Controle basique sur les top results retournes pendant les tests.

Remarque: les dates d'observation (`YYYY-MM-DD`) peuvent rester presentes car ce sont des dates cliniques utiles, pas forcement une fuite identitaire brute.

In [11]:
forbidden_text_patterns = [
    'PATIENT TEST1',
    'PYXIS TEST',
    'patient_id_raw',
    'ip_patient',
    'patient_birth_date_raw',
    'prescripteur',
    'validé(e) par',
    'edité(e) par',
    'imprimé par',
    'anonymization_mapping',
    'data/private/',
]

forbidden_metadata_keys = {
    'patient_id', 'patient_id_raw', 'ip_patient',
    'patient_birth_date', 'patient_birth_date_raw',
    'prescriber', 'validated_by', 'edited_by', 'printed_by',
    'phone', 'fax'
}

pii_rows = []

def scan_df(df: pd.DataFrame, suite: str):
    if df.empty:
        return
    for _, row in df.iterrows():
        txt = str(row.get('excerpt') or '')
        hits = [p for p in forbidden_text_patterns if p.lower() in txt.lower()]
        pii_rows.append({
            'suite': suite,
            'query': row.get('query'),
            'mode': row.get('mode'),
            'rank': row.get('rank'),
            'forbidden_text_hits': hits,
        })

for df in exact_detail:
    scan_df(df, 'exact_detail')
for df in smoke_tables:
    scan_df(df, 'smoke')

pii_df = pd.DataFrame(pii_rows)
if pii_df.empty:
    display(Markdown('Aucun resultat a scanner.'))
else:
    pii_df['has_hits'] = pii_df['forbidden_text_hits'].apply(lambda x: bool(x))
    display(pii_df[pii_df['has_hits'] == True])

# Metadata keys check from top results of smoke + exact first rows
meta_key_violations = []
for df in exact_detail + smoke_tables:
    if df.empty:
        continue
    # metadata details are not all flattened in df; this check is done via live calls

# No assert hard-fail: this notebook is evaluative and must remain inspectable.
print('PII sanity check terminé (revue visuelle recommandée).')

Empty DataFrame
Columns: [suite, query, mode, rank, forbidden_text_hits, has_hits]
Index: []

PII sanity check terminé (revue visuelle recommandée).

## 8) Optional: run retrieval validation script

Ce script applique les cas de test dans `tests/retrieval_test_cases.json` et calcule des métriques globales (Recall@K, MRR, etc.).

In [12]:
import subprocess

cmd = [
    sys.executable,
    str(repo_root / 'scripts' / 'retrieval' / 'validate_retrieval.py'),
    '--mode', 'all',
    '--top-k', '5',
    '--index-dir', str(INDEX_DIR),
    '--collection', COLLECTION,
    '--report', str(repo_root / 'data' / 'retrieval' / 'retrieval_validation_report.json'),
]

print('Commande:', ' '.join(cmd))
proc = subprocess.run(cmd, cwd=str(repo_root), capture_output=True, text=True)
print('exit_code =', proc.returncode)
print('--- stdout ---')
print(proc.stdout[:4000])
print('--- stderr ---')
print(proc.stderr[:2000])

Commande: /home/onizuka/Bureau/PFE/medical-rag-platform/venv/bin/python /home/onizuka/Bureau/PFE/medical-rag-platform/scripts/retrieval/validate_retrieval.py --mode all --top-k 5 --index-dir /home/onizuka/Bureau/PFE/medical-rag-platform/data/indexes --collection medical_chunks --report /home/onizuka/Bureau/PFE/medical-rag-platform/data/retrieval/retrieval_validation_report.json
exit_code = 1
--- stdout ---

--- stderr ---
Traceback (most recent call last):
  File "/home/onizuka/Bureau/PFE/medical-rag-platform/venv/lib/python3.12/site-packages/portalocker/portalocker.py", line 398, in lock
    self.locker(fd, flags)
BlockingIOError: [Errno 11] Resource temporarily unavailable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/onizuka/Bureau/PFE/medical-rag-platform/venv/lib/python3.12/site-packages/qdrant_client/local/qdrant_local.py", line 144, in _load
    portalocker.lock(
  File "/home/onizuka/Bureau/PFE/medical-rag-platform/venv/lib/python3.12/site-packages/portalocker/portalocker.py", line 441, in lock
    _posix_locker_instance.lock(file, flags)
  File "/home/onizuka/Bureau/PFE/medical-rag-platform/venv/lib/python3.12/site-packages/portalocker/portalocker.py", line 401, in lock
    raise exceptions.AlreadyLocked(
portalocker.exceptions.AlreadyLocked: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/onizuka/Bureau/PFE/medical-rag-platform/scripts/retrieval/validate_retrieval.py", line 786, in <module>
    raise SystemExit(main())
                     ^^^^^^
  File "/home/onizuka/Bureau/PFE/medical-rag-platform/scripts/retrieval/validate_retrieval.py", line 651, in main
    engine = SearchEngine(
             ^^^^^^^^^^^^^
  File "/home/onizuka/Bureau/PFE/medical-rag-platform/scripts/retrieval/search.py", line 65, in __init__
    self.qdrant_store = QdrantStore(qdrant_dir, collection_name=collection, embedding_model=embedding_model)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onizuka/Bureau/PFE/medical-rag-platform/scripts/retrieval/qdrant_store.py", line 91, in __init__
    self.client = QdrantClient(path=str(self.qdrant_dir))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/onizuka/Bureau/PFE/medic

## 9) Conclusion / Verdict

Interprétation recommandée:
- Si `hybrid` améliore Hit@3/Hit@5 vs `keyword` et `vector`, c'est un signal positif.
- Si les filtres metadata matchent correctement, c'est un bon signal de robustesse clinique.
- Si des fuites PII sont detectees, corriger avant toute demo publique.

Decision:
- Demo PFE: OK si smoke + exact queries sont coherentes et sans fuite evidente.
- Validation experimentale: OK si metrics stables sur `validate_retrieval.py`.
- Production-ready: non sans monitoring, jeu de tests elargi, et audit securite continu.

In [13]:
# Fermer proprement
engine.close()
print('SearchEngine fermé.')

SearchEngine fermé.